name: Release

on:
  release:
    types:
      - created

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish
        run: echo "FIXME"
