name: Test
on:
  push:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Lint
        run: npm run lint:check
      - name: Formatting
        run: npm run fmt:check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Test
        run: npm run test:cov
      - name: Report coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          fail_ci_if_error: true

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Build
        run: npm run build
      - name: Build
        run: npm run build:declarations
